server.port=443
server.ssl.enabled=true
server.ssl.key-store=/etc/letsencrypt/live/gtdistributing.com/keystore.p12
server.ssl.key-store-password=Welcome@GT
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tomcat
